name: 'GitGudSimilarIssues Action'

description: 'Get similar issues based on an issue title from GitGudIssues'

inputs:
  issuetitle:  
    description: 'Issue to analyze title'
    required: true
    default: 'Hello World'
  repo:
    description: 'Repository to analyze'
    required: true
  similaritytolerance:
    description: 'How low of a tolerance you will show issues for. 0 is not similar, 1 is identical'
    required: false
    default: "0.7"
  commentBody:
    description: 'Comment body to post'
    required: false
    default: |
      Hi I'm an AI powered bot that finds similar issues based off the issue title.
      
      Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!

outputs:
  message: 
    description: 'Output message'

runs:
  using: 'node20'
  main: 'dist/index.js'